[package]
name = "iter-map"
version = "0.1.0"
authors = ["ttappr <tmtappr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
